/**
 * BASE action catalog — paths and payload rules from pages/api/base/action/*.js
 */
export const BASE_ACTION_CATALOG = {
  state: {
    method: "GET",
    path: "/api/base/state",
    body: null,
    automation: "implemented",
    note: "Read BASE state",
  },
  build: {
    method: "POST",
    path: "/api/base/action/build",
    body: null,
    automation: "implemented",
    note: "building_key chosen from live BASE state (buildings + requires)",
  },
  research: {
    method: "POST",
    path: "/api/base/action/research",
    body: null,
    automation: "implemented",
    note: "research_key chosen from live BASE state (unlock order + prerequisites)",
  },
  maintenance: {
    method: "POST",
    path: "/api/base/action/maintenance",
    body: () => ({}),
    automation: "implemented",
    note: "RPC base_perform_maintenance — no body",
  },
  expedition: {
    method: "POST",
    path: "/api/base/action/expedition",
    body: () => ({}),
    automation: "implemented",
    note: "RPC base_launch_expedition — no body",
  },
  ship: {
    method: "POST",
    path: "/api/base/action/ship",
    body: () => ({}),
    automation: "implemented",
    note: "RPC base_ship_to_vault — no body",
  },
  crew: {
    method: "POST",
    path: "/api/base/action/crew",
    body: () => ({}),
    automation: "implemented",
    note: "RPC base_hire_crew — no body",
  },
  sector_deploy: {
    method: "POST",
    path: "/api/base/action/sector-deploy",
    body: () => ({}),
    automation: "implemented",
    note: "RPC base_deploy_next_sector — no body",
  },
  spend: {
    method: "POST",
    path: "/api/base/action/spend",
    body: null,
    automation: "implemented",
    note: "spend_type from live energy (refill when not near full)",
  },
  profile: {
    method: "POST",
    path: "/api/base/action/profile",
    body: () => ({}),
    automation: "implemented",
    note: "Empty body allowed (optional crew_role / commander_path)",
  },
  module: {
    method: "POST",
    path: "/api/base/action/module",
    body: null,
    automation: "coverage_gap",
    note: "Requires module_key from live BASE state — not guessed",
  },
  mission_claim: {
    method: "POST",
    path: "/api/base/action/mission-claim",
    body: null,
    automation: "coverage_gap",
    note: "Requires mission_key from live missions — not guessed",
  },
  contract_claim: {
    method: "POST",
    path: "/api/base/action/contract-claim",
    body: null,
    automation: "coverage_gap",
    note: "Requires contract_key from live contracts — not guessed",
  },
  command_protocol: {
    method: "POST",
    path: "/api/base/action/command-protocol",
    body: null,
    automation: "coverage_gap",
    note: "Requires protocol_id valid for unlocked protocols — not guessed",
  },
  unlock_support_program: {
    method: "POST",
    path: "/api/base/action/unlock-support-program",
    body: null,
    automation: "coverage_gap",
    note: "Requires building_key + program_key from state — not guessed",
  },
};

export const BASE_SCHEDULER_ACTIONS = [
  "state",
  "build",
  "research",
  "maintenance",
  "expedition",
  "ship",
  "crew",
  "sector_deploy",
  "spend",
  "profile",
  "module",
  "mission_claim",
  "contract_claim",
  "command_protocol",
  "unlock_support_program",
];
