/** 20 persistent QA personas — see plan Section 4. */
export const PERSONAS = [
  {
    id: "qa_ghost",
    displayName: "[QA] Ghost",
    seed: 101,
    dailyMinutesMin: 0,
    dailyMinutesMax: 10,
    activeDaysMin: 5,
    activeDaysMax: 8,
    moduleWeights: { miners: 0.25, base: 0.25, solo_v2: 0.25, ov2: 0.25 },
    risk: "none",
    maxDailyMinutes: 10,
    preferredWindows: ["morning"],
    games: { solo: "any", ov2: "light" },
    focus: "Near-absent user; server state across long gaps",
  },
  {
    id: "qa_drifter",
    displayName: "[QA] Drifter",
    seed: 102,
    dailyMinutesMin: 10,
    dailyMinutesMax: 30,
    activeDaysMin: 14,
    activeDaysMax: 18,
    moduleWeights: { miners: 0.6, base: 0.4, solo_v2: 0, ov2: 0 },
    risk: "low",
    maxDailyMinutes: 30,
    preferredWindows: ["morning", "evening"],
    games: { solo: "conservative", ov2: "none" },
    focus: "Light casual baseline economy",
  },
  {
    id: "qa_miner_core",
    displayName: "[QA] Miner Core",
    seed: 103,
    dailyMinutesMin: 60,
    dailyMinutesMax: 120,
    activeDaysMin: 25,
    activeDaysMax: 28,
    moduleWeights: { miners: 0.9, base: 0.1, solo_v2: 0, ov2: 0 },
    risk: "low",
    maxDailyMinutes: 120,
    preferredWindows: ["afternoon"],
    games: { solo: "none", ov2: "none" },
    focus: "Miners claim-to-vault over 30 days",
  },
  {
    id: "qa_base_ops",
    displayName: "[QA] Base Ops",
    seed: 104,
    dailyMinutesMin: 90,
    dailyMinutesMax: 180,
    activeDaysMin: 24,
    activeDaysMax: 28,
    moduleWeights: { miners: 0.1, base: 0.9, solo_v2: 0, ov2: 0 },
    risk: "low",
    maxDailyMinutes: 180,
    preferredWindows: ["afternoon"],
    games: { solo: "none", ov2: "none" },
    focus: "BASE build/research/expedition/ship",
  },
  {
    id: "qa_solo_safe",
    displayName: "[QA] Solo Safe",
    seed: 105,
    dailyMinutesMin: 45,
    dailyMinutesMax: 90,
    activeDaysMin: 20,
    activeDaysMax: 24,
    moduleWeights: { miners: 0, base: 0, solo_v2: 1, ov2: 0 },
    risk: "low",
    maxDailyMinutes: 90,
    preferredWindows: ["evening"],
    games: { solo: "conservative", ov2: "none" },
    focus: "Conservative Solo V2 EV drift",
  },
  {
    id: "qa_solo_risky",
    displayName: "[QA] Solo Risky",
    seed: 106,
    dailyMinutesMin: 60,
    dailyMinutesMax: 120,
    activeDaysMin: 20,
    activeDaysMax: 24,
    moduleWeights: { miners: 0, base: 0, solo_v2: 1, ov2: 0 },
    risk: "high",
    maxDailyMinutes: 120,
    preferredWindows: ["evening"],
    games: { solo: "aggressive", ov2: "none" },
    focus: "Aggressive Solo V2 abnormal gains",
  },
  {
    id: "qa_ov2_social",
    displayName: "[QA] OV2 Social",
    seed: 107,
    dailyMinutesMin: 60,
    dailyMinutesMax: 120,
    activeDaysMin: 22,
    activeDaysMax: 26,
    moduleWeights: { miners: 0, base: 0, solo_v2: 0, ov2: 1 },
    risk: "medium",
    maxDailyMinutes: 120,
    preferredWindows: ["evening"],
    games: { solo: "none", ov2: "social" },
    focus: "OV2 room lifecycle and Realtime",
  },
  {
    id: "qa_balanced",
    displayName: "[QA] Balanced",
    seed: 108,
    dailyMinutesMin: 60,
    dailyMinutesMax: 150,
    activeDaysMin: 22,
    activeDaysMax: 26,
    moduleWeights: { miners: 0.25, base: 0.25, solo_v2: 0.25, ov2: 0.25 },
    risk: "medium",
    maxDailyMinutes: 150,
    preferredWindows: ["morning", "evening"],
    games: { solo: "balanced", ov2: "social" },
    focus: "Cross-module economy interaction",
  },
  {
    id: "qa_daily_grind",
    displayName: "[QA] Daily Grind",
    seed: 109,
    dailyMinutesMin: 120,
    dailyMinutesMax: 240,
    activeDaysMin: 27,
    activeDaysMax: 30,
    moduleWeights: { miners: 0.4, base: 0.2, solo_v2: 0.4, ov2: 0 },
    risk: "medium",
    maxDailyMinutes: 240,
    preferredWindows: ["morning", "afternoon"],
    games: { solo: "balanced", ov2: "light" },
    focus: "Daily cap and vault accumulation",
  },
  {
    id: "qa_heavy_miner",
    displayName: "[QA] Heavy Miner",
    seed: 110,
    dailyMinutesMin: 240,
    dailyMinutesMax: 360,
    activeDaysMin: 26,
    activeDaysMax: 30,
    moduleWeights: { miners: 0.8, base: 0.2, solo_v2: 0, ov2: 0 },
    risk: "medium",
    maxDailyMinutes: 360,
    preferredWindows: ["afternoon"],
    games: { solo: "none", ov2: "none" },
    focus: "Heavy Miners cap enforcement",
  },
  {
    id: "qa_econ_tester",
    displayName: "[QA] Econ Tester",
    seed: 111,
    dailyMinutesMin: 120,
    dailyMinutesMax: 240,
    activeDaysMin: 24,
    activeDaysMax: 28,
    moduleWeights: { miners: 0.2, base: 0.3, solo_v2: 0.5, ov2: 0 },
    risk: "high",
    maxDailyMinutes: 240,
    preferredWindows: ["afternoon"],
    games: { solo: "aggressive", ov2: "none" },
    focus: "Duplicate rewards and vault races",
    rapidActions: true,
  },
  {
    id: "qa_max_player",
    displayName: "[QA] Max Player",
    seed: 112,
    dailyMinutesMin: 360,
    dailyMinutesMax: 480,
    activeDaysMin: 28,
    activeDaysMax: 30,
    moduleWeights: { miners: 0.2, base: 0.2, solo_v2: 0.35, ov2: 0.25 },
    risk: "high",
    maxDailyMinutes: 480,
    preferredWindows: ["morning", "afternoon", "evening"],
    games: { solo: "aggressive", ov2: "social" },
    focus: "Max usage stress and rate limits",
  },
  {
    id: "qa_skip_days",
    displayName: "[QA] Skip Days",
    seed: 113,
    dailyMinutesMin: 90,
    dailyMinutesMax: 180,
    activeDaysMin: 10,
    activeDaysMax: 14,
    moduleWeights: { miners: 0.5, base: 0.5, solo_v2: 0, ov2: 0 },
    risk: "low",
    maxDailyMinutes: 180,
    preferredWindows: ["morning"],
    games: { solo: "none", ov2: "none" },
    focus: "Persistence across multi-day gaps",
  },
  {
    id: "qa_burst",
    displayName: "[QA] Burst",
    seed: 114,
    dailyMinutesMin: 180,
    dailyMinutesMax: 300,
    activeDaysMin: 12,
    activeDaysMax: 16,
    moduleWeights: { miners: 0, base: 0, solo_v2: 0.6, ov2: 0.4 },
    risk: "high",
    maxDailyMinutes: 300,
    preferredWindows: ["burst"],
    games: { solo: "aggressive", ov2: "social" },
    focus: "Burst sessions then long offline",
  },
  {
    id: "qa_switcher",
    displayName: "[QA] Switcher",
    seed: 115,
    dailyMinutesMin: 90,
    dailyMinutesMax: 180,
    activeDaysMin: 20,
    activeDaysMax: 24,
    moduleWeights: { miners: 0.25, base: 0.25, solo_v2: 0.25, ov2: 0.25 },
    risk: "medium",
    maxDailyMinutes: 180,
    preferredWindows: ["afternoon"],
    games: { solo: "balanced", ov2: "light" },
    focus: "Mid-session module switching",
    rotateModules: true,
  },
  {
    id: "qa_long_session",
    displayName: "[QA] Long Session",
    seed: 116,
    dailyMinutesMin: 180,
    dailyMinutesMax: 300,
    activeDaysMin: 18,
    activeDaysMax: 22,
    moduleWeights: { miners: 0, base: 0, solo_v2: 0.4, ov2: 0.6 },
    risk: "medium",
    maxDailyMinutes: 300,
    preferredWindows: ["evening"],
    games: { solo: "balanced", ov2: "social" },
    focus: "Long sessions and Realtime reconnect",
    longSession: true,
  },
  {
    id: "qa_base_researcher",
    displayName: "[QA] Base Researcher",
    seed: 117,
    dailyMinutesMin: 90,
    dailyMinutesMax: 180,
    activeDaysMin: 24,
    activeDaysMax: 28,
    moduleWeights: { miners: 0, base: 1, solo_v2: 0, ov2: 0 },
    risk: "low",
    maxDailyMinutes: 180,
    preferredWindows: ["afternoon"],
    games: { solo: "none", ov2: "none" },
    focus: "Deep BASE progression",
  },
  {
    id: "qa_cashout_early",
    displayName: "[QA] Cashout Early",
    seed: 118,
    dailyMinutesMin: 45,
    dailyMinutesMax: 90,
    activeDaysMin: 20,
    activeDaysMax: 24,
    moduleWeights: { miners: 0, base: 0, solo_v2: 1, ov2: 0 },
    risk: "medium",
    maxDailyMinutes: 90,
    preferredWindows: ["evening"],
    games: { solo: "cashout", ov2: "none" },
    focus: "Partial-session vault delivery games",
  },
  {
    id: "qa_room_creator",
    displayName: "[QA] Room Creator",
    seed: 119,
    dailyMinutesMin: 60,
    dailyMinutesMax: 120,
    activeDaysMin: 22,
    activeDaysMax: 26,
    moduleWeights: { miners: 0, base: 0, solo_v2: 0, ov2: 1 },
    risk: "medium",
    maxDailyMinutes: 120,
    preferredWindows: ["evening"],
    games: { solo: "none", ov2: "rooms" },
    focus: "Room lifecycle and orphaned rooms",
  },
  {
    id: "qa_realtime_stress",
    displayName: "[QA] RT Stress",
    seed: 120,
    dailyMinutesMin: 120,
    dailyMinutesMax: 240,
    activeDaysMin: 24,
    activeDaysMax: 28,
    moduleWeights: { miners: 0, base: 0, solo_v2: 0.2, ov2: 0.8 },
    risk: "high",
    maxDailyMinutes: 240,
    preferredWindows: ["evening"],
    games: { solo: "light", ov2: "stress" },
    focus: "Realtime disconnect/reconnect stress",
    realtimeStress: true,
  },
];

export function getPersonaById(id) {
  return PERSONAS.find(p => p.id === id);
}

export function resolvePersonaList(args) {
  if (args.allUsers) return PERSONAS;
  if (args.users?.length) {
    return args.users.map(id => getPersonaById(id)).filter(Boolean);
  }
  return [];
}
