/**
 * Static session mocks for `/online-v2/game-ui-previews` only.
 * No Supabase — shapes mirror hook return values enough for UI rendering.
 */

import { ONLINE_V2_GAME_KINDS } from "../ov2Economy";

/** Dev / explicit flag only — keeps production builds free of this entry unless you opt in. */
export function isOv2UiPreviewsEnabled() {
  if (typeof process !== "undefined" && process.env.NEXT_PUBLIC_OV2_UI_PREVIEWS === "true") return true;
  if (typeof process !== "undefined" && process.env.NODE_ENV === "development") return true;
  return false;
}

const DEMO_ROOM_ID = "00000000-0000-4000-8000-000000000001";
const DEMO_SESS_ID = "00000000-0000-4000-8000-000000000002";
const PK_SELF = "ov2-ui-preview-self";

function noop() {}
async function noopOk() {
  return { ok: true };
}
async function noopOkFalse() {
  return { ok: false };
}

function fakeRoom(productId) {
  return {
    id: DEMO_ROOM_ID,
    product_game_id: productId,
    host_participant_key: PK_SELF,
    active_session_id: DEMO_SESS_ID,
    match_seq: 1,
    lifecycle_phase: "active",
  };
}

const members2 = [
  { participant_key: PK_SELF, seat_index: 0, wallet_state: "committed", display_name: "You (preview)", meta: {} },
  { participant_key: "ov2-ui-preview-opp", seat_index: 1, wallet_state: "committed", display_name: "Opponent", meta: {} },
];

/** @returns {{ room: object, members: unknown[], self: { participant_key: string, display_name: string }, onLeaveToLobby: () => Promise<void>, leaveToLobbyBusy: boolean }} */
export function buildPreviewContextInput(productGameId) {
  return {
    room: fakeRoom(productGameId),
    members: members2,
    self: { participant_key: PK_SELF, display_name: "You (preview)" },
    onLeaveToLobby: async () => {},
    leaveToLobbyBusy: false,
  };
}

const now = Date.now();
const turnDeadline = now + 60_000;
const matchEndMs = now + 60_000;

export function buildOv2UiPreviewMocks() {
  return {
    dominoes: {
      snapshot: {
        phase: "playing",
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnSeat: 0,
        mySeat: 0,
        myHand: [
          { a: 1, b: 6 },
          { a: 2, b: 5 },
          { a: 3, b: 3 },
        ],
        oppHandCount: 5,
        boneyardCount: 8,
        line: [
          { lo: 4, hi: 4 },
          { lo: 4, hi: 2 },
        ],
        missedTurns: { 0: 0, 1: 0 },
        turnDeadline,
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canClientPlayTiles: true,
        canOfferDouble: false,
        mustRespondDouble: false,
        result: null,
      },
      vm: {
        phase: "playing",
        line: [
          { lo: 4, hi: 4 },
          { lo: 4, hi: 2 },
        ],
        board: {},
        turnSeat: 0,
        mySeat: 0,
        winnerSeat: null,
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnDeadline,
        turnTimeLeftMs: 60_000,
        turnTimeLeftSec: 60,
        doubleDeadlineMs: null,
        doubleTimeLeftMs: null,
        doubleTimeLeftSec: null,
        missedStreakBySeat: { 0: 0, 1: 0 },
        myHand: [
          { a: 1, b: 6 },
          { a: 2, b: 5 },
          { a: 3, b: 3 },
        ],
        oppHandCount: 5,
        boneyardCount: 8,
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canClientPlayTiles: true,
        canOfferDouble: false,
        mustRespondDouble: false,
        result: null,
        resultWinner: null,
        resultDraw: false,
        resultBlocked: false,
        resultEmptyHand: false,
        resultDoubleDeclined: false,
        resultDoubleTimeout: false,
        resultTimeoutLoserSeat: null,
        resultForfeitBy: "",
        resultPrize: null,
        resultLossPerSeat: null,
        resultStakeMultiplier: null,
        resultPipTotalsBySeat: null,
      },
      busy: false,
      vaultClaimBusy: false,
      settlementPrizeAmount: null,
      err: "",
      setErr: noop,
      playTile: noopOk,
      drawOne: noopOk,
      passTurn: noopOk,
      offerDouble: noopOk,
      respondDouble: noopOk,
      requestRematch: noopOk,
      cancelRematch: noopOk,
      startNextMatch: noopOk,
      isHost: true,
      roomMatchSeq: 1,
    },

    fourline: {
      snapshot: {
        phase: "playing",
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnSeat: 0,
        mySeat: 0,
        cells: Array.from({ length: 42 }, (_, i) => {
          const row = Math.floor(i / 7);
          const col = i % 7;
          if (row === 5 && col === 3) return 0;
          if (row === 4 && col === 3) return 1;
          if (row === 5 && col === 2) return 0;
          return null;
        }),
        missedTurns: { 0: 0, 1: 0 },
        turnDeadline,
        lastMove: { col: 3, seat: 0 },
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canOfferDouble: false,
        mustRespondDouble: false,
      },
      vm: {
        phase: "playing",
        turnSeat: 0,
        mySeat: 0,
        winnerSeat: null,
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnDeadline,
        turnTimeLeftSec: 60,
        missedStreakBySeat: { 0: 0, 1: 0 },
        cells: Array.from({ length: 42 }, (_, i) => {
          const row = Math.floor(i / 7);
          const col = i % 7;
          if (row === 5 && col === 3) return 0;
          if (row === 4 && col === 3) return 1;
          if (row === 5 && col === 2) return 0;
          return null;
        }),
        lastMove: { col: 3, seat: 0 },
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canOfferDouble: false,
        mustRespondDouble: false,
        baseStakePerSeat: 500,
        chipsPerSeatAtStake: 500,
        chipsPrizeTotal: 1000,
      },
      busy: false,
      vaultClaimBusy: false,
      err: "",
      setErr: noop,
      playColumn: noopOk,
      offerDouble: noopOk,
      respondDouble: noopOk,
      requestRematch: noopOk,
      cancelRematch: noopOk,
      startNextMatch: noopOk,
      isHost: true,
      roomMatchSeq: 1,
    },

    flipgrid: {
      snapshot: {
        phase: "playing",
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnSeat: 0,
        mySeat: 0,
        cells: Array.from({ length: 64 }, (_, i) => (i % 9 === 0 ? 1 : i % 11 === 0 ? 2 : 0)),
        discCounts: { 0: 28, 1: 27 },
        missedTurns: { 0: 0, 1: 0 },
        turnDeadline,
        turnHolderLegalMoveCount: 4,
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canOfferDouble: false,
        mustRespondDouble: false,
      },
      vm: {
        phase: "playing",
        turnSeat: 0,
        mySeat: 0,
        winnerSeat: null,
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnDeadline,
        turnTimeLeftSec: 60,
        missedStreakBySeat: { 0: 0, 1: 0 },
        cells: Array.from({ length: 64 }, (_, i) => (i % 9 === 0 ? 1 : i % 11 === 0 ? 2 : 0)),
        discCounts: { 0: 28, 1: 27 },
        turnHolderLegalMoveCount: 4,
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canOfferDouble: false,
        mustRespondDouble: false,
      },
      busy: false,
      vaultClaimBusy: false,
      err: "",
      setErr: noop,
      playCell: noopOk,
      offerDouble: noopOk,
      respondDouble: noopOk,
      requestRematch: noopOk,
      cancelRematch: noopOk,
      startNextMatch: noopOk,
      isHost: true,
      roomMatchSeq: 1,
    },

    meldmatch: {
      snapshot: {
        phase: "playing",
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnSeat: 0,
        turnPhase: "play",
        mySeat: 0,
        stockCount: 40,
        discardCount: 3,
        discardTop: { rank: "7", suit: "hearts" },
        handSizes: [10, 10],
        myHand: [
          { rank: "A", suit: "spades" },
          { rank: "K", suit: "hearts" },
        ],
        opponentHandCount: 10,
        opponentHandRevealed: [],
        layoffMelds: null,
        missedTurns: { 0: 0, 1: 0 },
        turnDeadline,
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canOfferDouble: false,
        mustRespondDouble: false,
        result: null,
      },
      vm: {
        phase: "playing",
        turnSeat: 0,
        turnPhase: "play",
        mySeat: 0,
        winnerSeat: null,
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnDeadline,
        turnTimeLeftSec: 60,
        missedStreakBySeat: { 0: 0, 1: 0 },
        stockCount: 40,
        discardCount: 3,
        discardTop: { rank: "7", suit: "hearts" },
        handSizes: [10, 10],
        myHand: [
          { rank: "A", suit: "spades" },
          { rank: "K", suit: "hearts" },
        ],
        opponentHandCount: 10,
        opponentHandRevealed: [],
        layoffCloserSeat: null,
        layoffCloserDeadwood: null,
        layoffMelds: null,
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        canOfferDouble: false,
        mustRespondDouble: false,
        result: null,
      },
      busy: false,
      vaultClaimBusy: false,
      err: "",
      setErr: noop,
      draw: noopOk,
      discard: noopOk,
      declareFinish: noopOk,
      resolveLayoff: noopOk,
      offerDouble: noopOk,
      respondDouble: noopOk,
      requestRematch: noopOk,
      cancelRematch: noopOk,
      startNextMatch: noopOk,
      isHost: true,
      roomMatchSeq: 1,
    },

    colorclash: {
      snapshot: {
        phase: "playing",
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnSeat: 0,
        turnPhase: "play",
        mySeat: 0,
        stockCount: 20,
        discardCount: 2,
        topDiscard: { color: "red", kind: "skip" },
        currentColor: "blue",
        direction: 1,
        handCounts: { 0: 5, 1: 5 },
        eliminated: { 0: false, 1: false },
        activeSeats: [0, 1],
        playerCount: 2,
        myHand: [
          { color: "blue", kind: "number", n: 5 },
          { color: "green", kind: "draw_two" },
        ],
        pendingDrawForYou: null,
        missedTurns: { 0: 0, 1: 0, 2: 0, 3: 0 },
        turnDeadline,
        result: null,
        clashCount: 0,
        lockedColor: null,
        lockForSeat: null,
        lockExpiresAfterNextTurn: false,
        surgeUsedBySeat: { "0": false, "1": false },
        surgeUsedForYou: false,
      },
      vm: {
        phase: "playing",
        turnSeat: 0,
        turnPhase: "play",
        mySeat: 0,
        winnerSeat: null,
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnDeadline,
        turnTimeLeftSec: 60,
        missedStreakBySeat: { 0: 0, 1: 0, 2: 0, 3: 0 },
        stockCount: 20,
        discardCount: 2,
        topDiscard: { color: "red", kind: "skip" },
        currentColor: "blue",
        direction: 1,
        handCounts: { 0: 5, 1: 5 },
        eliminated: { 0: false, 1: false },
        activeSeats: [0, 1],
        playerCount: 2,
        myHand: [
          { color: "blue", kind: "number", n: 5 },
          { color: "green", kind: "draw_two" },
        ],
        pendingDrawForYou: null,
        clashCount: 0,
        lockedColor: null,
        lockForSeat: null,
        lockExpiresAfterNextTurn: false,
        wildLockAppliesToMe: false,
        surgeUsedForMe: false,
        surgeAvailableForMe: true,
        surgeUsedBySeat: { "0": false, "1": false },
        surgeUsedForYou: false,
        result: null,
      },
      busy: false,
      vaultClaimBusy: false,
      err: "",
      setErr: noop,
      drawCard: noopOk,
      passAfterDraw: noopOk,
      playCard: noopOk,
      requestRematch: noopOk,
      cancelRematch: noopOk,
      startNextMatch: noopOk,
      isHost: true,
      roomMatchSeq: 1,
    },

    fleethunt: {
      snapshot: {
        phase: "battle",
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnSeat: 0,
        mySeat: 0,
        turnDeadline,
        placementDl: { 0: now + 999_999, 1: now + 999_999 },
        missedTurns: { 0: 0, 1: 0 },
        placementMissed: { 0: 0, 1: 0 },
        lock0: true,
        lock1: true,
        shots0: [{ r: 0, c: 0, hit: false }],
        shots1: [{ r: 3, c: 4, hit: true }],
        myShips: [
          { r: 0, c: 0, w: 1, h: 4 },
        ],
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        result: null,
      },
      vm: {
        phase: "battle",
        turnSeat: 0,
        mySeat: 0,
        winnerSeat: null,
        revision: 1,
        sessionId: DEMO_SESS_ID,
        turnDeadline,
        turnTimeLeftSec: 45,
        placementTimeLeftSec: null,
        missedStreakBySeat: { 0: 0, 1: 0 },
        placementMissStreakBySeat: { 0: 0, 1: 0 },
        lock0: true,
        lock1: true,
        shots0: [{ r: 0, c: 0, hit: false }],
        shots1: [{ r: 3, c: 4, hit: true }],
        myShips: [
          { r: 0, c: 0, w: 1, h: 4 },
        ],
        stakeMultiplier: 1,
        doublesAccepted: 0,
        pendingDouble: null,
        result: null,
      },
      busy: false,
      vaultClaimBusy: false,
      err: "",
      setErr: noop,
      submitPlacement: noopOk,
      randomPlacement: noopOk,
      lockPlacement: noopOk,
      fireShot: noopOk,
      offerDouble: noopOk,
      respondDouble: noopOk,
      requestRematch: noopOk,
      cancelRematch: noopOk,
      startNextMatch: noopOk,
      isHost: true,
      roomMatchSeq: 1,
    },

    goalduel: {
      snapshot: {
        phase: "playing",
        revision: 1,
        sessionId: DEMO_SESS_ID,
        mySeat: 0,
        score0: 1,
        score1: 0,
        matchEndMs,
        public: {
          arena: { w: 800, h: 400, groundY: 360, goalMargin: 48 },
          p0: { x: 180, y: 338, hw: 14, hh: 22 },
          p1: { x: 620, y: 338, hw: 14, hh: 22 },
          ball: { x: 400, y: 220, r: 11 },
        },
        result: null,
      },
      vm: {
        phase: "playing",
        mySeat: 0,
        winnerSeat: null,
        revision: 1,
        sessionId: DEMO_SESS_ID,
        public: {
          arena: { w: 800, h: 400, groundY: 360, goalMargin: 48 },
          p0: { x: 180, y: 338, hw: 14, hh: 22 },
          p1: { x: 620, y: 338, hw: 14, hh: 22 },
          ball: { x: 400, y: 220, r: 11 },
        },
        score0: 1,
        score1: 0,
        myScore: 1,
        matchEndMs,
        matchTimeLeftSec: 60,
        result: null,
      },
      busy: false,
      vaultClaimBusy: false,
      err: "",
      setErr: noop,
      setInput: noop,
      inputRef: { current: { l: false, r: false, j: false, k: false } },
      requestRematch: noopOk,
      cancelRematch: noopOk,
      startNextMatch: noopOk,
      isHost: true,
      roomMatchSeq: 1,
    },
  };
}

export function previewTabs() {
  return [
    { id: "dominoes", title: "Dominoes", productId: ONLINE_V2_GAME_KINDS.DOMINOES },
    { id: "fourline", title: "FourLine", productId: ONLINE_V2_GAME_KINDS.FOURLINE },
    { id: "flipgrid", title: "FlipGrid", productId: ONLINE_V2_GAME_KINDS.FLIPGRID },
    { id: "meldmatch", title: "MeldMatch", productId: ONLINE_V2_GAME_KINDS.MELDMATCH },
    { id: "colorclash", title: "Color Clash", productId: ONLINE_V2_GAME_KINDS.COLOR_CLASH },
    { id: "fleethunt", title: "Fleet Hunt", productId: ONLINE_V2_GAME_KINDS.FLEET_HUNT },
    { id: "goalduel", title: "Goal Duel", productId: ONLINE_V2_GAME_KINDS.GOAL_DUEL },
  ];
}
