import { ProfileSettings } from "./types";

export const PROFILES: ProfileSettings[] = [
  {
    name: "casual",
    population: 12_000,
    redeemableSpendBudgetPctPerDay: 0.45,
    miners: {
      activeBreaksPerDay: 220,
      offlineBreaksPerDay: 180,
      moveToVaultRate: 0.55,
      claimToVaultPerDay: 1,
      stageResetEveryBreaks: 180,
      stageStart: 1,
      stageStartDriftPerDay: 0.01,
    },
    base: {
      logisticsLevel: 2,
      blueprintStartLevel: 2,
      powerCellLevel: 2,
      hasCoolant: true,
      refineryLevel: 2,
      activeSecondsPerDay: 3600,
      offlineEffectiveFactor: 0.28,
      shipsPerDay: 0.4,
      spendBlueprintPerDay: 0.05,
      spendOverclockPerDay: 0.12,
      spendRefillPerDay: 0.28,
    },
    arcade: {
      paidSessionsPerDay: 5,
      paidStake: 1200,
      paidMix: { low: 0.55, medium: 0.35, high: 0.1 },
      freeplaySessionsPerDay: 6,
      freeplayAvgReward: 70,
    },
  },
  {
    name: "normal",
    population: 30_000,
    redeemableSpendBudgetPctPerDay: 0.55,
    miners: {
      activeBreaksPerDay: 900,
      offlineBreaksPerDay: 500,
      moveToVaultRate: 0.75,
      claimToVaultPerDay: 3,
      stageResetEveryBreaks: 260,
      stageStart: 4,
      stageStartDriftPerDay: 0.02,
    },
    base: {
      logisticsLevel: 5,
      blueprintStartLevel: 6,
      powerCellLevel: 5,
      hasCoolant: true,
      refineryLevel: 5,
      activeSecondsPerDay: 7200,
      offlineEffectiveFactor: 0.33,
      shipsPerDay: 1.0,
      spendBlueprintPerDay: 0.10,
      spendOverclockPerDay: 0.22,
      spendRefillPerDay: 0.45,
    },
    arcade: {
      paidSessionsPerDay: 12,
      paidStake: 2800,
      paidMix: { low: 0.45, medium: 0.4, high: 0.15 },
      freeplaySessionsPerDay: 7,
      freeplayAvgReward: 80,
    },
  },
  {
    name: "aggressive",
    population: 50_000,
    redeemableSpendBudgetPctPerDay: 0.70,
    miners: {
      activeBreaksPerDay: 2400,
      offlineBreaksPerDay: 1200,
      moveToVaultRate: 0.85,
      claimToVaultPerDay: 4,
      stageResetEveryBreaks: 420,
      stageStart: 10,
      stageStartDriftPerDay: 0.05,
    },
    base: {
      logisticsLevel: 9,
      blueprintStartLevel: 14,
      powerCellLevel: 9,
      hasCoolant: true,
      refineryLevel: 9,
      activeSecondsPerDay: 18000,
      offlineEffectiveFactor: 0.4,
      shipsPerDay: 2.5,
      spendBlueprintPerDay: 0.18,
      spendOverclockPerDay: 0.45,
      spendRefillPerDay: 0.9,
    },
    arcade: {
      paidSessionsPerDay: 28,
      paidStake: 5500,
      paidMix: { low: 0.3, medium: 0.45, high: 0.25 },
      freeplaySessionsPerDay: 9,
      freeplayAvgReward: 95,
    },
  },
  {
    name: "offline-heavy",
    population: 20_000,
    redeemableSpendBudgetPctPerDay: 0.50,
    miners: {
      activeBreaksPerDay: 420,
      offlineBreaksPerDay: 1800,
      moveToVaultRate: 0.68,
      claimToVaultPerDay: 2,
      stageResetEveryBreaks: 220,
      stageStart: 3,
      stageStartDriftPerDay: 0.015,
    },
    base: {
      logisticsLevel: 4,
      blueprintStartLevel: 5,
      powerCellLevel: 4,
      hasCoolant: true,
      refineryLevel: 4,
      activeSecondsPerDay: 7200,
      offlineEffectiveFactor: 0.45,
      shipsPerDay: 0.75,
      spendBlueprintPerDay: 0.07,
      spendOverclockPerDay: 0.18,
      spendRefillPerDay: 0.35,
    },
    arcade: {
      paidSessionsPerDay: 4,
      paidStake: 1800,
      paidMix: { low: 0.5, medium: 0.35, high: 0.15 },
      freeplaySessionsPerDay: 10,
      freeplayAvgReward: 70,
    },
  },
];
