-- BASE debug: איפוס רך — מחזיר בסיס לברירת מחדל אך שומר audit. החלף PUT-DEVICE-ID-HERE
update public.base_device_state
set
  banked_mleo = 0,
  sent_today = 0,
  total_banked = 0,
  total_shared_spent = 0,
  total_missions_done = 0,
  total_expeditions = 0,
  commander_level = 1,
  commander_xp = 0,
  blueprint_level = 0,
  crew = 0,
  crew_role = 'engineer',
  commander_path = 'industry',
  overclock_until = null,
  expedition_ready_at = now(),
  maintenance_due = 0,
  stability = 100,
  resources = public.base_default_resources(),
  buildings = public.base_default_buildings(),
  paused_buildings = '{}'::jsonb,
  building_power_modes = '{}'::jsonb,
  modules = '{}'::jsonb,
  research = '{}'::jsonb,
  stats = public.base_default_stats(),
  mission_state = public.base_default_mission_state(current_date::text),
  contract_state = public.base_default_contract_state(),
  log = '[]'::jsonb,
  mleo_produced_today = 0,
  last_day = current_date,
  last_tick_at = now(),
  updated_at = now()
where device_id = 'PUT-DEVICE-ID-HERE';
